### PR TITLE
Turbostroi v3

### PR DESCRIPTION
**Pull request by SmileDoge**
новый турбострой переписанный на расте

позволяет установить на linux
по идее немного быстрее
стоит проверить

сам модуль
https://github.com/SmileDoge/gm_turbostroi_rust/releases/tag/v3.0.1

### CODE REVIEW

**Review by LennDoMations — APPROVED** [review]
Great succesor to the V2 from OnlyNoob. I am looking forward to seing it being used in the original metrostroi!

**Comment by LennDoMations** [comment]
@HellReach

**Comment by ElectricityMachine** [comment]
After some testing, the V3 Turbostroi performs considerably worse on my Windows 10 LTSC server. On gm_metro_minsk_1984, I get around 5-7 wagons _less_ before the server starts to lag compared to V2. In addition, I've encountered a bug where most of the switches' animations don't synchronize properly when their position is updated. It's reproducible if you spawn the 81-717 Moscow Head in a fully started config.

If you need any more info, @ me and I can provide screenshots, console logs, or graphs of CPU usage over time.

**Comment by SmileDoge** [comment]
@ElectricityMachine can you send value of turbostroi_train_cores?

**Comment by CrIcKeT98** [comment]
Будет выложен как отдельный репозиторий.

**Pull request closed without merging**
